version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: mindscribe:latest
        container_name: mindscribe
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "--spider", "http://localhost:3000/users"]
            interval: 30s
            timeout: 10s
            start_period: 10s
            retries: 2
